### ISSUE TITLE
1gb üstü dosyalarda çöküyor.

### ISSUE THREAD

**Issue by ghost** [merty/simple-file-uploader#3]
Uygulamanı çalıştırdım ancak fark ettiğim bir durum var. 1 gb üstü dosya yüklemek istediğim zaman çöküyor nodejs tarafı çalışmayı durduruyor ve chrome'da çökme uyarısı çıkıyor diğer tarayıcılarda yükleniyorda kalıyor.

**Comment by darrencauthon** [comment]
Google Translate:  "I run the application, but there is a situation that I noticed. Over 1 GB file crashes when I want to install nodejs side stops and goes to work in Chrome crash warning remains in yükleniyor in other browsers."

**Comment by merty** [comment]
Tamamen HTML5 File API'ının ve Node.js'in kullanımına örnek olması amacıyla yazılmış bir proje olduğundan kodu basit tutmak adına dosya tek parça olarak gönderiliyor. Bu da ciddi anlamda dosya transferi için kullanmanın sağlıklı (ve bazı durumlarda mümkün) olmayacağı anlamına geliyor.

Dosya transferi ihtiyaçlarını karşılayacak daha kapsamlı ayrı bir uygulamayı önümüzdeki birkaç hafta içerisinde paylaşıyor olacağım.
