### ISSUE TITLE
Upload percentage

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [merty/simple-file-uploader#4]
Hi
Is there any feature in your module which will show How much a file is uploaded in percentage?

**Comment by merty** [comment]
First of all, sorry for the late response!

This project is purely for demonstration purposes only and to keep things simple, I'm not planning to add any more features.

I see there are many people who are actually interested in a file uploader they can run on their servers so I'm planning to release a separate project for that in the upcoming weeks.

Stay tuned!
