### ISSUE TITLE
Could be responsive?

### ISSUE THREAD

**Issue by pedro-nonfree** [merty/simple-file-uploader#5]
Could be added responsiveness to the application and remain simple?

**Comment by merty** [comment]
Could you please explain what exactly you mean with responsiveness?

This was actually a project I put together for demonstration purposes only. Seeing that people are actually interested in it, I'm planning to rewrite the project from the scratch soon :)

**Comment by pedro-nonfree** [comment]
It is an awesome project, because is a very easy way to share with your friends files without needing a USB pen drive =)

I think this could be a project like http-server
https://www.npmjs.com/package/http-server

Responsiveness I mean that If I reduce width, the frame is not reduced. Could be useful when you are seeing it with mobile phones, etc.

**Comment by merty** [comment]
Really nice to hear that :)

Alright, noted! I'll be releasing a new version in a few days, stay tuned!

**Comment by merty** [comment]
Just released version 0.2.0 with a bit of responsiveness :)

https://github.com/merty/simple-file-uploader/commit/1076272a579947d0116e45ef56e3779835210893
